/**
 * @file configs/sidebar.ts
 * @brief Contains the SidebarConfig object.
 * @copyright Copyright (c) 2022 FreeBSD Chinese Community. All rights reserved.
 */

import type {SidebarConfig} from '@vuepress/theme-default';

export const sideBarConfig: SidebarConfig = [
  {
    text: 'FreeBSD 从入门到跑路',
    children: ['/README.md'],
  },
  {
    text: '第〇章 FreeBSD 中文社区',
    children: [
      '/di-ling-zhang-freebsd-zhong-wen-she-qu/di-yi-jie-freebsd-faq.md',
      '/di-ling-zhang-freebsd-zhong-wen-she-qu/di-er-jie-freebsd-zhong-wen-she-qu-cfc-fa-zhan-gui-hua.md',
      '/di-ling-zhang-freebsd-zhong-wen-she-qu/di-san-jie-freebsd-de-bu-zu-zhi-chu.md',
      '/di-ling-zhang-freebsd-zhong-wen-she-qu/di-si-jie-freebsd-fa-hang-shuo-ming.md',
    ],
  },
  {
    text: '第一章 走近 FreeBSD',
    children: [
      '/di-yi-zhang-zou-jin-freebsd/di-yi-jie-shi-mo-shi-unix.md',
      '/di-yi-zhang-zou-jin-freebsd/di-er-jie-shi-mo-shi-lei-unix.md',
      '/di-yi-zhang-zou-jin-freebsd/di-san-jie-shi-mo-shi-linux.md',
      '/di-yi-zhang-zou-jin-freebsd/di-si-jie-freebsd-yu-qi-ta-cao-zuo-xi-tong.md',
      '/di-yi-zhang-zou-jin-freebsd/di-wu-jie-wei-shi-mo-yao-shi-yong-freebsd.md',
      '/di-yi-zhang-zou-jin-freebsd/di-liu-jie-suo-wei-kai-yuan-zhe-xue.md',
      '/di-yi-zhang-zou-jin-freebsd/di-qi-jie-qi-ta-bsd-jian-jie.md',
      '/di-yi-zhang-zou-jin-freebsd/di-ba-jie-linux-yong-hu-qian-yi-zhi-bei.md',
      '/di-yi-zhang-zou-jin-freebsd/di-jiu-jie-can-kao-zi-liao-yu-gong-xian-zhe-ming-dan.md',
      '/di-yi-zhang-zou-jin-freebsd/di-shi-jie-bian-zhuan-shuo-ming.md',
    ],
  },
  {
    text: '第二章 安装 FreeBSD',
    children: [
      '/di-er-zhang-an-zhuang-freebsd/di-ling-jie-tu-jie-an-zhuang.md',
      '/di-er-zhang-an-zhuang-freebsd/di-yi-jie-san-zhong-xu-ni-ji-yu-freebsd-ban-ben-bi-jiao.md',
      '/di-er-zhang-an-zhuang-freebsd/di-er-jie-freebsd-an-zhuang-ji-yu-virtual-box.md',
      '/di-er-zhang-an-zhuang-freebsd/di-san-jie-freebsd-13.0-an-zhuang-ji-yu-vmware-workstation-pro-16.md',
      '/di-er-zhang-an-zhuang-freebsd/di-si-jie-teng-xun-yun-qing-liang-yun-ji-qi-ta-fu-wu-qi-dd-an-zhuang-freebsd.md',
      '/di-er-zhang-an-zhuang-freebsd/di-wu-jie-shou-dong-an-zhuang-freebsd.md',
      '/di-er-zhang-an-zhuang-freebsd/di-liu-jie-ee-yong-fa-ji-wang-luo-pei-zhi.md',
      '/di-er-zhang-an-zhuang-freebsd/di-qi-jie-chang-yong-ruan-jian-yu-ssh-pei-zhi.md',
      '/di-er-zhang-an-zhuang-freebsd/di-ba-jie-wu-li-ji-an-zhuang-yu-ying-jian-xuan-pei.md',
      '/di-er-zhang-an-zhuang-freebsd/di-jiu-jie-wu-li-ji-xia-xian-ka-de-pei-zhi.md',
      '/di-er-zhang-an-zhuang-freebsd/di-shi-jie-wu-li-ji-xia-chu-mo-ban-de-she-zhi.md',
      '/di-er-zhang-an-zhuang-freebsd/di-shi-yi-jie-wu-li-ji-sheng-ka-yu-wang-ka-she-zhi.md',
      '/di-er-zhang-an-zhuang-freebsd/di-shi-er-jie-da-yin-ji-de-an-zhuang.md',
      '/di-er-zhang-an-zhuang-freebsd/di-shi-san-jie-wu-xian-lan-ya-shu-biao-de-she-zhi.md',
    ],
  },
  {
    text: '第三章 软件源及包管理器',
    children: [
      '/di-san-zhang-ruan-jian-yuan-ji-bao-guan-li-qi/di-ling-jie-bao-guan-li-qi-gai-shu.md',
      '/di-san-zhang-ruan-jian-yuan-ji-bao-guan-li-qi/di-yi-jie-freebsd-jing-xiang-zhan-xian-zhuang.md',
      '/di-san-zhang-ruan-jian-yuan-ji-bao-guan-li-qi/di-er-jie-freebsd-huan-yuan-fang-shi.md',
      '/di-san-zhang-ruan-jian-yuan-ji-bao-guan-li-qi/di-san-jie-gitup-de-yong-fa.md',
      '/di-san-zhang-ruan-jian-yuan-ji-bao-guan-li-qi/di-si-jie-ruan-jian-bao-guan-li-qi-pkg-de-yong-fa.md',
      '/di-san-zhang-ruan-jian-yuan-ji-bao-guan-li-qi/di-wu-jie-tong-guo-yuan-dai-ma-port-fang-shi-an-zhuang-ruan-jian.md',
      '/di-san-zhang-ruan-jian-yuan-ji-bao-guan-li-qi/di-liu-jie-tong-guo-dvd-an-zhuang-ruan-jian.md',
    ],
  },
  {
    text: '第四章 桌面安装',
    children: [
      '/di-si-zhang-zhuo-mian-an-zhuang/di-ling-jie-gai-shu.md',
      '/di-si-zhang-zhuo-mian-an-zhuang/di-yi-jie-an-zhuang-xorg.md',
      '/di-si-zhang-zhuo-mian-an-zhuang/di-er-jie-an-zhuang-kde-5.md',
      '/di-si-zhang-zhuo-mian-an-zhuang/di-san-jie-an-zhuang-gnome.md',
      '/di-si-zhang-zhuo-mian-an-zhuang/di-si-jie-an-zhuang-mate.md',
      '/di-si-zhang-zhuo-mian-an-zhuang/di-wu-jie-an-zhuang-xfce.md',
      '/di-si-zhang-zhuo-mian-an-zhuang/di-liu-jie-an-zhuang-cinnamon.md',
      '/di-si-zhang-zhuo-mian-an-zhuang/di-qi-jie-an-zhuang-lumina.md',
      '/di-si-zhang-zhuo-mian-an-zhuang/di-ba-jie-root-deng-lu-zhuo-mian.md',
      '/di-si-zhang-zhuo-mian-an-zhuang/di-jiu-jie-zhu-ti-yu-mei-hua.md',
      '/di-si-zhang-zhuo-mian-an-zhuang/di-shi-jie-yuan-cheng-zhuo-mian-guan-li.md',
      '/di-si-zhang-zhuo-mian-an-zhuang/di-shi-yi-jie-an-zhuang-wayland-ke-xuan.md',
    ],
  },
  {
    text: '第五章 输入法及常用软件',
    children: [
      '/di-wu-zhang-shu-ru-fa-ji-chang-yong-ruan-jian/di-yi-jie-fcitx-shu-ru-fa-kuang-jia.md',
      '/di-wu-zhang-shu-ru-fa-ji-chang-yong-ruan-jian/di-er-jie-ibus-shu-ru-fa-kuang-jia.md',
      '/di-wu-zhang-shu-ru-fa-ji-chang-yong-ruan-jian/di-san-jie-qi-ta-shu-ru-fa-kuang-jia.md',
      '/di-wu-zhang-shu-ru-fa-ji-chang-yong-ruan-jian/di-si-jie-firefox-yu-chromium-an-zhuang.md',
      '/di-wu-zhang-shu-ru-fa-ji-chang-yong-ruan-jian/di-wu-jie-linux-jian-rong-ceng.md',
      '/di-wu-zhang-shu-ru-fa-ji-chang-yong-ruan-jian/di-liu-jie-an-zhuang-jin-shan-wps.md',
      '/di-wu-zhang-shu-ru-fa-ji-chang-yong-ruan-jian/di-qi-jie-an-zhuang-qq.md',
      '/di-wu-zhang-shu-ru-fa-ji-chang-yong-ruan-jian/di-ba-jie-geng-huan-zi-ti.md',
      '/di-wu-zhang-shu-ru-fa-ji-chang-yong-ruan-jian/di-jiu-jie-wine.md',
      '/di-wu-zhang-shu-ru-fa-ji-chang-yong-ruan-jian/di-shi-jie-ya-suo-yu-jie-ya.md',
    ],
  },
  {
    text: '第六章 文件系统与磁盘管理',
    children: [
      '/di-liu-zhang-wen-jian-xi-tong-yu-ci-pan-guan-li/di-yi-jie-ufs.md',
      '/di-liu-zhang-wen-jian-xi-tong-yu-ci-pan-guan-li/di-er-jie-zfs.md',
      '/di-liu-zhang-wen-jian-xi-tong-yu-ci-pan-guan-li/di-san-jie-ci-pan-kuo-rong.md',
      '/di-liu-zhang-wen-jian-xi-tong-yu-ci-pan-guan-li/di-si-jie-ntfs-de-gua-zai.md',
      '/di-liu-zhang-wen-jian-xi-tong-yu-ci-pan-guan-li/di-wu-jie-swap-jiao-huan-fen-qu-de-she-zhi.md',
      '/di-liu-zhang-wen-jian-xi-tong-yu-ci-pan-guan-li/di-liu-jie-ext-234-deng-wen-jian-xi-tong.md',
    ],
  },
  {
    text: '第七章 VPN 与代理',
    children: [
      '/di-qi-zhang-vpn-yu-dai-li/di-yi-jie-http-dai-li.md',
      '/di-qi-zhang-vpn-yu-dai-li/di-er-jie-v2ray.md',
      '/di-qi-zhang-vpn-yu-dai-li/di-san-jie-clash.md',
      '/di-qi-zhang-vpn-yu-dai-li/di-si-jie-openvpn.md',
      '/di-qi-zhang-vpn-yu-dai-li/di-wu-jie-wireguard.md',
    ],
  },
  {
    text: '第八章 用户与权限',
    children: [
      '/di-ba-zhang-yong-hu-yu-quan-xian/di-yi-jie-sudo-huo-dash-de-an-zhuang.md',
      '/di-ba-zhang-yong-hu-yu-quan-xian/di-er-jie-tian-jia-yong-hu.md',
      '/di-ba-zhang-yong-hu-yu-quan-xian/di-san-jie-yong-hu-zu.md',
      '/di-ba-zhang-yong-hu-yu-quan-xian/di-si-jie-yong-hu-quan-xian.md',
    ],
  },
  {
    text: '第九章 Jail',
    children: [
      '/di-jiu-zhang-jail/di-yi-jie-jail-yu-docker-de-bi-jiao.md',
      '/di-jiu-zhang-jail/di-er-jie-jail-xiang-guan-shu-yu.md',
      '/di-jiu-zhang-jail/di-san-jie-jail-pei-zhi.md',
      '/di-jiu-zhang-jail/di-si-jie-jail-geng-xin.md',
      '/di-jiu-zhang-jail/di-wu-jie-shi-yong-ezjail-guan-li-jail.md',
    ],
  },
  {
    text: '第十章 虚拟化',
    children: [
      '/di-shi-zhang-xu-ni-hua/di-yi-jie-xu-ni-hua-jian-jie.md',
      '/di-shi-zhang-xu-ni-hua/di-er-jie-an-zhuang-virtual-box.md',
      '/di-shi-zhang-xu-ni-hua/di-san-jie-an-zhuang-bhyve.md',
      '/di-shi-zhang-xu-ni-hua/di-si-jie-shi-yong-cbsd-guan-li-bhyve.md',
      '/di-shi-zhang-xu-ni-hua/di-wu-jie-shi-yong-bhyve-an-zhuang-windows-11.md',
      '/di-shi-zhang-xu-ni-hua/di-liu-jie-an-zhuang-xen.md',
      '/di-shi-zhang-xu-ni-hua/di-qi-jie-shi-yong-xen-an-zhuang-windows-11.md',
    ],
  },
  {
    text: '第十一章 更新与升级 FreeBSD',
    children: [
      '/di-shi-yi-zhang-geng-xin-yu-sheng-ji-freebsd/di-yi-jie-tong-guo-freebsdupdate-geng-xin.md',
      '/di-shi-yi-zhang-geng-xin-yu-sheng-ji-freebsd/di-er-jie-tong-guo-yuan-dai-ma-geng-xin.md',
      '/di-shi-yi-zhang-geng-xin-yu-sheng-ji-freebsd/di-san-jie-pi-liang-bu-shu.md',
    ],
  },
  {
    text: '第十二章 GEOM 存储框架',
    children: [
      '/di-shi-er-zhang-geom-cun-chu-kuang-jia/di-yi-jie-gai-shu.md',
      '/di-shi-er-zhang-geom-cun-chu-kuang-jia/di-er-jie-raid-0.md',
      '/di-shi-er-zhang-geom-cun-chu-kuang-jia/di-san-jie-raid-1.md',
      '/di-shi-er-zhang-geom-cun-chu-kuang-jia/di-si-jie-raid-3.md',
      '/di-shi-er-zhang-geom-cun-chu-kuang-jia/di-wu-jie-ruan-raid-pei-zhi.md',
      '/di-shi-er-zhang-geom-cun-chu-kuang-jia/di-liu-jie-geom-gate-network.md',
      '/di-shi-er-zhang-geom-cun-chu-kuang-jia/di-qi-jie-ci-pan-zhuang-zhi-biao-qian.md',
      '/di-shi-er-zhang-geom-cun-chu-kuang-jia/di-ba-jie-ufs-journaling-yu-geom.md',
      '/di-shi-er-zhang-geom-cun-chu-kuang-jia/di-jiu-jie-zfs-ci-pan-jia-jie-mi.md',
    ],
  },
  {
    text: '第十三章 DTrace',
    children: [
      '/di-shi-san-zhang-dtrace/di-yi-jie-gai-shu.md',
      '/di-shi-san-zhang-dtrace/di-er-jie-kai-qi-dtrace.md',
      '/di-shi-san-zhang-dtrace/di-san-jie-shi-yong-dtrace.md',
    ],
  },
  {
    text: '第十四章 网络管理',
    children: [
      '/di-shi-si-zhang-wang-luo-guan-li/di-yi-jie-ppp-bo-hao.md',
      '/di-shi-si-zhang-wang-luo-guan-li/di-er-jie-wifi.md',
      '/di-shi-si-zhang-wang-luo-guan-li/di-san-jie-usb-rndis-usb-wang-luo-gong-xiang.md',
      '/di-shi-si-zhang-wang-luo-guan-li/di-si-jie-lan-ya.md',
      '/di-shi-si-zhang-wang-luo-guan-li/di-wu-jie-ipv6.md',
      '/di-shi-si-zhang-wang-luo-guan-li/di-liu-jie-carp.md',
      '/di-shi-si-zhang-wang-luo-guan-li/di-qi-jie-vlan.md',
      '/di-shi-si-zhang-wang-luo-guan-li/di-ba-jie-tcp-bbr.md',
    ],
  },
  {
    text: '第十五章 FreeBSD 防火墙',
    children: [
      '/di-shi-wu-zhang-freebsd-fang-huo-qiang/di-yi-jie-wang-luo-can-shu-pei-zhi-ming-ling.md',
      '/di-shi-wu-zhang-freebsd-fang-huo-qiang/di-er-jie-pf.md',
      '/di-shi-wu-zhang-freebsd-fang-huo-qiang/di-san-jie-ipfw.md',
      '/di-shi-wu-zhang-freebsd-fang-huo-qiang/di-si-jie-ipfilter-ipf.md',
    ],
  },
  {
    text: '第十六章 服务器',
    children: [
      '/di-shi-liu-zhang-fu-wu-qi/di-yi-jie-ftp-fu-wu-qi.md',
      '/di-shi-liu-zhang-fu-wu-qi/di-er-jie-dhcp-fu-wu-qi.md',
      '/di-shi-liu-zhang-fu-wu-qi/di-san-jie-nodejs-xiang-guan.md',
      '/di-shi-liu-zhang-fu-wu-qi/di-si-jie-dns-fu-wu-qi.md',
      '/di-shi-liu-zhang-fu-wu-qi/di-wu-jie-nis-fu-wu-qi.md',
      '/di-shi-liu-zhang-fu-wu-qi/di-liu-jie-postfix-fu-wu-qi.md',
      '/di-shi-liu-zhang-fu-wu-qi/di-qi-jie-samba-fu-wu-qi.md',
      '/di-shi-liu-zhang-fu-wu-qi/di-ba-jie-nfs-fu-wu-qi.md',
      '/di-shi-liu-zhang-fu-wu-qi/di-jiu-jie-iscsi.md',
      '/di-shi-liu-zhang-fu-wu-qi/di-shi-jie-webmin.md',
      '/di-shi-liu-zhang-fu-wu-qi/di-shi-yi-jie-rsync-tong-bu-fu-wu.md',
      '/di-shi-liu-zhang-fu-wu-qi/di-shi-er-jie-shi-jian-fu-wu.md',
      '/di-shi-liu-zhang-fu-wu-qi/di-shi-san-jie-wildfly.md',
    ],
  },
  {
    text: '第十七章 网络服务器',
    children: [
      '/di-shi-qi-zhang-wang-luo-fu-wu-qi/di-yi-jie-apache.md',
      '/di-shi-qi-zhang-wang-luo-fu-wu-qi/di-er-jie-nginx.md',
      '/di-shi-qi-zhang-wang-luo-fu-wu-qi/di-san-jie-php-8.x.md',
      '/di-shi-qi-zhang-wang-luo-fu-wu-qi/di-si-jie-mysql-5.x.md',
      '/di-shi-qi-zhang-wang-luo-fu-wu-qi/di-wu-jie-mysql-8.x.md',
      '/di-shi-qi-zhang-wang-luo-fu-wu-qi/di-liu-jie-typecho.md',
      '/di-shi-qi-zhang-wang-luo-fu-wu-qi/di-qi-jie-ssl-pei-zhi.md',
      '/di-shi-qi-zhang-wang-luo-fu-wu-qi/di-ba-jie-postgresql-yu-pgadmin4.md',
    ],
  },
  {
    text: '第十八章 树莓派与嵌入式',
    children: [
      '/di-shi-ba-zhang-shu-mei-pai-yu-qian-ru-shi/di-yi-jie-shu-mei-pai-jian-jie.md',
      '/di-shi-ba-zhang-shu-mei-pai-yu-qian-ru-shi/di-er-jie-xi-tong-an-zhuang.md',
      '/di-shi-ba-zhang-shu-mei-pai-yu-qian-ru-shi/di-san-jie-shi-yong-pei-zhi.md',
      '/di-shi-ba-zhang-shu-mei-pai-yu-qian-ru-shi/di-si-jie-usb-wang-ka-yu-wifi.md',
      '/di-shi-ba-zhang-shu-mei-pai-yu-qian-ru-shi/di-wu-jie-riscv.md',
    ],
  },
  {
    text: '第十九章 文学故事',
    children: [
      '/di-shi-jiu-zhang-wen-xue-gu-shi/di-yi-jie-wo-yu-freebsd-de-gu-shi.md',
      '/di-shi-jiu-zhang-wen-xue-gu-shi/di-er-jie-freebsd-yu-mao-xuan-ze-1-de-sheng-huo.md',
      '/di-shi-jiu-zhang-wen-xue-gu-shi/di-san-jie-linux-yu-ku-nan-zhe-xue.md',
      '/di-shi-jiu-zhang-wen-xue-gu-shi/di-si-jie-cong-yi-ge-xiang-fa-kan-freebsd-shi-shang-ye-hua-huan-shi-xue-yuan-pai.md',
      '/di-shi-jiu-zhang-wen-xue-gu-shi/di-wu-jie-linux-she-qu-yi-jing-cheng-wei-le-yi-ge-ang-zang-de-ni-tan.md',
      '/di-shi-jiu-zhang-wen-xue-gu-shi/di-liu-jie-linux-bai-ju-yi-ding.md',
      '/di-shi-jiu-zhang-wen-xue-gu-shi/di-qi-jie-xiao-shuo-freebsd-cong-ru-men-dao-pao-lu.md',
    ],
  },
  {
    text: '第二十章 娱乐与教育',
    children: [
      '/di-er-shi-zhang-yu-le-yu-jiao-yu/di-yi-jie-you-xi.md',
      '/di-er-shi-zhang-yu-le-yu-jiao-yu/di-er-jie-yin-shi-pin-bo-fang-qi.md',
      '/di-er-shi-zhang-yu-le-yu-jiao-yu/di-san-jie-yin-shi-pin-jian-ji.md',
      '/di-er-shi-zhang-yu-le-yu-jiao-yu/di-si-jie-jiao-yu.md',
      '/di-er-shi-zhang-yu-le-yu-jiao-yu/di-wu-jie-ke-yan-yu-zhuan-ye-gong-ju.md',
    ],
  },
  {
    text: '第二十一章 内核',
    children: [
      '/di-er-shi-yi-zhang-nei-he/di-yi-jie-huo-qu-freebsd-nei-he-yuan-ma.md',
      '/di-er-shi-yi-zhang-nei-he/di-er-jie-xiu-gai-nei-he-yuan-ma.md',
      '/di-er-shi-yi-zhang-nei-he/di-san-jie-bian-yi-nei-he.md',
      '/di-er-shi-yi-zhang-nei-he/di-si-jie-nei-he-fen-xi.md',
    ],
  },
  {
    text: '第二十二章 编程与开发',
    children: [
      '/di-er-shi-er-zhang-bian-cheng-yu-kai-fa/di-yi-jie-ru-he-bao-gao-bug.md',
      '/di-er-shi-er-zhang-bian-cheng-yu-kai-fa/di-er-jie-ru-he-ti-jiao-yi-ge-ruan-jian-bao.md',
      '/di-er-shi-er-zhang-bian-cheng-yu-kai-fa/di-san-jie-ru-he-can-yu-freebsd-xie-zuo.md',
      '/di-er-shi-er-zhang-bian-cheng-yu-kai-fa/di-si-jie-cc++-huan-jing-de-pei-zhi.md',
      '/di-er-shi-er-zhang-bian-cheng-yu-kai-fa/di-wu-jie-java-huan-jing-de-pei-zhi.md',
      '/di-er-shi-er-zhang-bian-cheng-yu-kai-fa/di-liu-jie-qt-huan-jing-de-pei-zhi.md',
      '/di-er-shi-er-zhang-bian-cheng-yu-kai-fa/di-qi-jie-python-yu-vscode.md',
      '/di-er-shi-er-zhang-bian-cheng-yu-kai-fa/di-ba-jie-rust-huan-jing-de-pei-zhi.md',
      '/di-er-shi-er-zhang-bian-cheng-yu-kai-fa/di-jiu-jie-shell-de-xuan-ze.md',
      '/di-er-shi-er-zhang-bian-cheng-yu-kai-fa/di-shi-jie-tong-guo-ida-7-tiao-shi-freebsd.md',
      '/di-er-shi-er-zhang-bian-cheng-yu-kai-fa/di-shi-yi-jie-git.md',
    ],
  },
  {
    text: '第二十三章 引导与恢复',
    children: [
      '/di-er-shi-san-zhang-yin-dao-yu-hui-fu/di-yi-jie-hui-fu-mo-shi-yu-mi-ma-zhong-zhi.md',
      '/di-er-shi-san-zhang-yin-dao-yu-hui-fu/di-er-jie-freebsd-duo-ying-pan-efi-yin-dao-tong-yi.md',
      '/di-er-shi-san-zhang-yin-dao-yu-hui-fu/di-san-jie-freebsd-zhong-wen-tty-kong-zhi-tai.md',
      '/di-er-shi-san-zhang-yin-dao-yu-hui-fu/di-si-jie-yin-dao-jie-mian.md',
      '/di-er-shi-san-zhang-yin-dao-yu-hui-fu/di-wu-jie-grub-ji-qi-ta-yin-dao.md',
    ],
  },
  {
    text: '第二十四章 FreeBSD 特色',
    children: [
      '/di-er-shi-si-zhang-freebsd-te-se/di-yi-jie-bsd-init-guan-li-fu-wu.md',
      '/di-er-shi-si-zhang-freebsd-te-se/di-er-jie-freebsd-mu-lu-jie-gou.md',
      '/di-er-shi-si-zhang-freebsd-te-se/di-san-jie-bsdinstall-yu-bsdconfig.md',
      '/di-er-shi-si-zhang-freebsd-te-se/di-si-jie-jin-yong-sendmail.md',
      '/di-er-shi-si-zhang-freebsd-te-se/di-wu-jie-li-yong-jiao-ben-zi-dong-sheng-cheng-bsdlibc-ku-wen-ben.md',
      '/di-er-shi-si-zhang-freebsd-te-se/di-liu-jie-bsd-feng-ge-de-makegrepsedawk.md',
    ],
  },
  {
    text: '第二十五章 系统设计与分析',
    children: [
      '/di-er-shi-wu-zhang-xi-tong-she-ji-yu-fen-xi/di-yi-jie-freebsd-she-ji-gai-yao.md',
      '/di-er-shi-wu-zhang-xi-tong-she-ji-yu-fen-xi/di-er-jie-nei-he.md',
      '/di-er-shi-wu-zhang-xi-tong-she-ji-yu-fen-xi/di-san-jie-jin-cheng.md',
      '/di-er-shi-wu-zhang-xi-tong-she-ji-yu-fen-xi/di-si-jie-nei-cun-guan-li.md',
      '/di-er-shi-wu-zhang-xi-tong-she-ji-yu-fen-xi/di-wu-jie-an-quan.md',
      '/di-er-shi-wu-zhang-xi-tong-she-ji-yu-fen-xi/di-liu-jie-io-xi-tong.md',
    ],
  },
  {
    text: '第二十六章 OpenBSD',
    children: [
      '/di-er-shi-liu-zhang-openbsd/di-ling-jie-gai-shu.md',
      '/di-er-shi-liu-zhang-openbsd/di-yi-jie-an-zhuang.md',
      '/di-er-shi-liu-zhang-openbsd/di-er-jie-pei-zhi.md',
      '/di-er-shi-liu-zhang-openbsd/di-san-jie-huan-yuan.md',
      '/di-er-shi-liu-zhang-openbsd/di-si-jie-bao-guan-li-qi.md',
      '/di-er-shi-liu-zhang-openbsd/di-wu-jie-zhuo-mian-yu-qi-ta-ruan-jian.md',
    ],
  },
  {
    text: '第二十七章 NetBSD',
    children: [
      '/di-er-shi-qi-zhang-netbsd/di-ling-jie-gai-shu.md',
      '/di-er-shi-qi-zhang-netbsd/di-yi-jie-an-zhuang-yu-pei-zhi.md',
      '/di-er-shi-qi-zhang-netbsd/di-er-jie-huan-yuan-yu-bao-guan-li-qi.md',
      '/di-er-shi-qi-zhang-netbsd/di-san-jie-zhuo-mian-yu-qi-ta-ruan-jian.md',
    ],
  },
  {
    text: '第二十八章 DragonFlyBSD',
    children: [
      '/di-er-shi-ba-zhang-dragonflybsd/di-ling-jie-gai-shu.md',
      '/di-er-shi-ba-zhang-dragonflybsd/di-yi-jie-an-zhuang-yu-pei-zhi.md',
    ],
  },
  {
    text: '第二十九章 桌面高级进阶',
    children: [
      '/di-er-shi-jiu-zhang-zhuo-mian-gao-ji-jin-jie/di-ling-jie-chuang-kou-guan-li-qi-yu-zhuo-mian-de-qu-bie-yu-lian-xi.md',
      '/di-er-shi-jiu-zhang-zhuo-mian-gao-ji-jin-jie/di-yi-jie-an-zhuang-i3wm.md',
      '/di-er-shi-jiu-zhang-zhuo-mian-gao-ji-jin-jie/di-er-jie-an-zhuang-cde.md',
      '/di-er-shi-jiu-zhang-zhuo-mian-gao-ji-jin-jie/di-san-jie-an-zhuang-awesome.md',
      '/di-er-shi-jiu-zhang-zhuo-mian-gao-ji-jin-jie/di-san-jie-an-zhuang-fvwm.md',
    ],
  },
];
